- name: copy bashrc
  ansible.builtin.template: 
    src: .bashrc
    dest: ~/.bashrc

- name: copy pureline config
  ansible.builtin.template:
    src: .pureline.conf
    dest: ~/.pureline.conf

- name: clone pureline
  ansible.builtin.git:
    repo: https://github.com/chris-marsh/pureline.git
    dest: ~/pureline