- name: copy bashrc
  template: 
    src: .bashrc
    dest: ~/.bashrc

- name: copy pureline config
  template:
    src: .pureline.conf
    dest: ~/.pureline.conf

- name: clone pureline
  git:
    repo: https://github.com/chris-marsh/pureline.git
    dest: ~/pureline